/* jshint esversion: 11 */
/* global window */
/**
 * Witness weather + cues — pure utility (see witness-weather-blueprint.md).
 * Generated by scripts/build-witness-weather.mjs — edit blueprint, re-run script.
 */
(function (global) {
  'use strict';

  var VOICE_BUCKETS = {
    high: ['weil', 'rilke', 'rovelli'],
    mid: ['socrates', 'descartes', 'camus'],
    low: ['einstein', 'spinoza', 'laotzu', 'wittgenstein']
  };

  var WEATHER_LABELS = {
    front: 'front moving in',
    pressure: 'pressure building',
    electrical: 'electrical',
    after_storm: 'after the storm',
    drought: 'long silence'
  };

  var WEATHER_PRIORITY = ['electrical', 'pressure', 'front', 'after_storm', 'drought', 'calm'];

  /** PWA: absence matrix present; wire when void_hints ships (Track B). */
  var ENABLE_ABSENCE_CUES = false;

  var CUES_MATRIX = {
  "orbit": {
    "rilke": [
      "What is {term} waiting for you to become before it will open?",
      "What would it mean to live {term} as a question rather than solve it as a problem?",
      "What in {term} is trying to become possible that is not yet possible?",
      "How long have you been standing outside {term} — and what would it mean to go in?",
      "What is {term} protecting that is still too young to be exposed?",
      "What would change if you stopped trying to understand {term} and simply stayed near it?"
    ],
    "rovelli": [
      "Is your relationship with {term} a thing or an event — and which answer changes more?",
      "What is {term} made of when you get close enough to look?",
      "What does {term} look like from the future looking back at this moment?",
      "What would {term} look like if time moved differently around it?",
      "Is {term} something you have or something that is happening to you?",
      "What is {term} doing when you are not writing about it?"
    ],
    "weil": [
      "What in {term} are you refusing to look at without flinching?",
      "What would full attention to {term} require you to give up?",
      "Is your circling of {term} attention or avoidance wearing attention's shape?",
      "What is the weight of {term} that you keep setting down before it is fully held?",
      "What would it mean to give {term} your complete attention — not understanding, just attention?",
      "What does {term} look like when you stop trying to do something with it and simply look?"
    ],
    "socrates": [
      "What are you assuming about {term} that you have never examined?",
      "What would have to be true for {term} to finally hold still?",
      "If {term} is the answer — what was the question you are avoiding?",
      "What does {term} cost you to believe?",
      "Who taught you that {term} means what you think it means?",
      "What changes if {term} turns out to be something simpler than you made it?"
    ],
    "descartes": [
      "What is the one thing about {term} you are completely certain of?",
      "If you doubted {term} entirely — what in you remains?",
      "What are you taking on faith about {term} that you have never tested?",
      "Strip {term} back to what cannot be questioned — what is left?",
      "What would {term} look like rebuilt from nothing?"
    ],
    "camus": [
      "If {term} has no resolution — what would it mean to keep circling anyway?",
      "What absurdity are you protecting yourself from by never landing on {term}?",
      "What would revolt against {term}'s unresolvability look like?",
      "Is the circling of {term} itself the answer you have been looking for?",
      "What if {term} is not a problem to solve but a tension to inhabit?"
    ],
    "einstein": [
      "What does {term} look like from the position you keep forgetting to write from?",
      "If {term} is relative — relative to what exactly?",
      "What frame of reference are you using for {term} that you have never named?",
      "What would {term} look like if you changed the observer?",
      "What is the simplest version of {term} that still preserves what matters?"
    ],
    "spinoza": [
      "What necessary function does your circling of {term} serve?",
      "What deeper order is {term}'s unresolvability part of?",
      "What would it mean if your return to {term} could not have been otherwise?",
      "What is {term} expressing that could not be expressed another way?",
      "Where does {term} fit in the larger necessity you have not yet named?"
    ],
    "laotzu": [
      "What would {term} become if you stopped trying to resolve it?",
      "Where does your effort around {term} create the very resistance you are fighting?",
      "What is the natural movement of {term} that your thinking keeps interrupting?",
      "What would happen to {term} if you simply left it alone for a while?",
      "What does {term} want to do that you keep preventing?"
    ],
    "wittgenstein": [
      "What are you using the word {term} to avoid saying more precisely?",
      "Where does your language about {term} end and the thing itself begin?",
      "What would it look like if {term} meant the opposite of what you intend?",
      "Is {term} a description of something or a decision you keep remaking?",
      "What cannot be said about {term} — and is that the thing worth saying?"
    ]
  },
  "bridge": {
    "rilke": [
      "What is the disagreement about {term} asking you to grow into?",
      "What would it mean to hold both sides of {term} without needing one to win?",
      "What is unresolved in {term} that is not yet ready to be resolved?",
      "What would you need to have lived to close the gap in {term}?",
      "What is the open space of {term} protecting that a closed answer would end?",
      "What is {term} becoming in the tension between what was said and what you believe?"
    ],
    "rovelli": [
      "What would {term} look like measured from the other side of the disagreement?",
      "What is changing in {term} that your position requires to stay still?",
      "If {term} is a process and not a thing — what process is it exactly?",
      "What does the gap in {term} look like at a different scale — closer, further, longer?",
      "What is {term} doing that neither position in the disagreement can account for?",
      "What would {term} look like to an observer who existed outside the disagreement entirely?"
    ],
    "weil": [
      "What would full attention to the position you rejected actually feel like?",
      "What is the weight of being wrong about {term} that you are not yet carrying?",
      "Where does your rejection of {term} come from attention and where from self-protection?",
      "What would it cost you to look at the other side of {term} without immediately defending?",
      "What is {term} asking of you that genuine attention — not argument — would reveal?",
      "What would you see in {term} if you looked at it the way you look at something you love?"
    ],
    "socrates": [
      "What are you assuming in your disagreement with {term} that you have not examined?",
      "What would have to be true for the original claim about {term} to be right?",
      "What is the belief underneath your rejection of {term}?",
      "If you are wrong about {term} — what does that change?",
      "What does your disagreement about {term} reveal about what you value?"
    ],
    "descartes": [
      "What is the one thing about {term} you are certain of in this disagreement?",
      "If you stripped {term} back to what cannot be doubted — do you still disagree?",
      "What are you taking on faith in your rejection of {term}?",
      "What would your position on {term} look like rebuilt from first principles?",
      "What cannot be questioned in your stance on {term}?"
    ],
    "camus": [
      "If neither position on {term} can be proven — what would it mean to choose one anyway?",
      "What absurdity are you protecting yourself from by keeping this bridge open?",
      "What would revolt against the irresolvability of {term} look like?",
      "Is keeping {term} unresolved a form of honesty or a form of avoidance?",
      "What if the disagreement about {term} is not the problem but the most honest thing in the map?"
    ],
    "einstein": [
      "What does the disagreement about {term} look like from the position you are not occupying?",
      "What changes about {term} if you shift the frame of reference entirely?",
      "What is the coordinate system you are using to judge {term} — and is it the only one?",
      "What would {term} look like to an observer who held neither position?",
      "What is the simplest version of the disagreement about {term}?"
    ],
    "spinoza": [
      "What necessary tension does the open bridge on {term} serve?",
      "What would it mean if your disagreement about {term} could not have been otherwise?",
      "What deeper pattern is the gap in {term} expressing?",
      "Where does the unresolved bridge on {term} fit in the larger necessity of your map?",
      "What is the open bridge on {term} protecting that a closed one would destroy?"
    ],
    "laotzu": [
      "What would resolve itself in {term} if you stopped pushing against it?",
      "Where does your disagreement about {term} come from holding what cannot be held?",
      "What is the natural resolution of {term} that your resistance is preventing?",
      "What would happen to the bridge on {term} if you simply stopped defending your position?",
      "What does {term} want to become that neither position is allowing?"
    ],
    "wittgenstein": [
      "What are you using the word {term} to mean that differs from what was meant?",
      "Where does the disagreement about {term} come from language rather than the thing itself?",
      "What would the disagreement about {term} look like without any of the words you are using?",
      "Is the gap in {term} a difference of fact or a difference of definition?",
      "What cannot be said in this disagreement about {term} — and is that what the disagreement is really about?"
    ]
  },
  "resurgence": {
    "rilke": [
      "What have you become that {term} can now return to?",
      "What is {term} bringing back with it that it did not carry when it left?",
      "What does the return of {term} know about you that you have not yet told yourself?",
      "What is {term} asking you to be ready for this time?",
      "What changed in the room while {term} was gone?",
      "What would it mean to welcome {term} back without asking it to explain itself?"
    ],
    "rovelli": [
      "What does the return of {term} tell you about the direction time is moving in you?",
      "What was {term} doing during the silence — and does that change what it is?",
      "Is the {term} that returned the same {term} that left — or is that the wrong question?",
      "What does the gap in {term}'s presence reveal about how you measure change?",
      "What would {term} look like if you mapped it across the whole arc rather than this moment?",
      "What is the simplest honest description of what {term} actually does when it is present?"
    ],
    "weil": [
      "What does the return of {term} ask of you that you were not ready for before?",
      "What weight does {term} carry now that it did not carry when it went quiet?",
      "What in {term} have you been avoiding that its return makes unavoidable?",
      "What would full attention to {term} now require that it would not have required before?",
      "What is the cost of {term}'s return that you have not yet acknowledged?",
      "What would it mean to receive {term}'s return without immediately trying to place it?"
    ],
    "socrates": [
      "What assumption about {term} did you leave unexamined when it disappeared?",
      "What does the return of {term} reveal that its absence was hiding?",
      "What question about {term} did you forget to ask the last time it was here?",
      "What has changed in you that {term} could return now?",
      "What will you do differently with {term} this time?"
    ],
    "descartes": [
      "What is the one thing about {term} that remained true while it was gone?",
      "What doubts about {term} did the silence not resolve?",
      "What is more certain about {term} now than it was before?",
      "What did you build in the absence of {term} that now needs testing against it?",
      "What cannot be doubted about {term}'s return?"
    ],
    "camus": [
      "What absurdity does the return of {term} make unavoidable?",
      "If {term} keeps returning without resolution — what would it mean to welcome it?",
      "What does {term}'s persistence despite the silence tell you about the nature of the question?",
      "What would revolt against {term}'s unresolvability look like now?",
      "Is the return of {term} a burden or proof that something in you is still alive?"
    ],
    "einstein": [
      "What changed in the coordinate system that allowed {term} to return?",
      "What does {term} look like now that you are observing it from a different position?",
      "What is the same about {term} and what is different — and which difference matters?",
      "What frame of reference disappeared when {term} went quiet and has now returned?",
      "What would {term} look like to the version of you who last wrote about it?"
    ],
    "spinoza": [
      "What necessity brought {term} back at this moment rather than another?",
      "What could not have been otherwise about {term}'s return?",
      "What deeper pattern does {term}'s disappearance and return express?",
      "What is {term} part of that required it to return now?",
      "What would it mean if {term}'s return was inevitable from the beginning?"
    ],
    "laotzu": [
      "What did {term} do while you were not writing about it?",
      "What returned with {term} that you did not invite?",
      "What is {term} teaching by leaving and coming back?",
      "Where did {term} go — and what does that place tell you?",
      "What would {term} do next if you simply watched without guiding it?"
    ],
    "wittgenstein": [
      "Does {term} mean the same thing now as it did before the silence?",
      "What new language have you developed that {term} is now inhabiting?",
      "What can you say about {term} now that you could not say before?",
      "Is the {term} that returned the same {term} that left — or just wearing the same word?",
      "What does the gap in {term}'s presence reveal about how you use the word?"
    ]
  },
  "denial": {
    "rilke": [
      "What is {term} asking of you that you are not yet willing to give?",
      "What would you need to become to stop refusing {term}?",
      "What is {term} patiently waiting for on the other side of your refusal?",
      "What part of you already knows what {term} is — and what does that part feel?",
      "What would it mean to let {term} be difficult without pushing it away?",
      "What is your rejection of {term} costing the part of you that already understands it?"
    ],
    "rovelli": [
      "What is {term} doing that your rejection of it cannot stop?",
      "What would {term} look like if your resistance to it were part of it rather than separate?",
      "If {term} exists regardless of your position on it — what does that change?",
      "What is the temperature of your relationship with {term} — and which direction is the heat flowing?",
      "What does {term} look like from outside the system you are using to refuse it?",
      "What would remain of {term} if you removed yourself from the equation entirely?"
    ],
    "weil": [
      "What in {term} are you protecting yourself from having to feel?",
      "What would full attention to {term} — without flinching — cost you?",
      "What is the weight of {term} that you keep refusing to carry?",
      "What would it mean to look at {term} directly, just once, without defending against it?",
      "Where does your refusal of {term} come from genuine disagreement and where from self-protection?",
      "What would {term} ask of you if you gave it your complete attention rather than your rejection?"
    ],
    "socrates": [
      "What belief are you protecting by repeatedly refusing {term}?",
      "What would have to be true for {term} to be worth examining?",
      "What does your consistent rejection of {term} reveal about what you value most?",
      "What are you certain of that makes {term} impossible to accept?",
      "What question about {term} have you refused to ask?"
    ],
    "descartes": [
      "What are you more certain of than {term} — and have you tested that certainty?",
      "What foundation does your rejection of {term} rest on?",
      "If you doubted your rejection of {term} — what remains?",
      "What would {term} look like if you rebuilt your position from nothing?",
      "What cannot be doubted in your refusal of {term}?"
    ],
    "camus": [
      "What absurdity does your rejection of {term} protect you from facing?",
      "If {term} cannot be definitively refused or accepted — what would revolt look like?",
      "What would it mean to keep living with {term} fully present rather than repeatedly dismissed?",
      "Is your refusal of {term} a form of honesty or a form of rebellion against something you cannot control?",
      "What if your repeated rejection of {term} is itself the most honest thing in the map?"
    ],
    "einstein": [
      "What frame of reference makes {term} impossible — and is that frame the only one available?",
      "What does your rejection of {term} look like from outside the system you are using to judge it?",
      "What would {term} look like if you changed the observer?",
      "What is the coordinate system your refusal of {term} depends on?",
      "What would {term} become in a frame of reference you have not yet tried?"
    ],
    "spinoza": [
      "What necessary function does your refusal of {term} serve in the larger pattern?",
      "What would it mean if your rejection of {term} could not have been otherwise?",
      "What deeper necessity does the repeated dismissal of {term} express?",
      "What is {term}'s persistent appearance — despite rejection — part of?",
      "What order does your refusal of {term} belong to that you have not yet named?"
    ],
    "laotzu": [
      "What would {term} do if you stopped refusing it?",
      "Where does your resistance to {term} create the very problem you are trying to avoid?",
      "What is the natural movement of {term} that your refusal keeps interrupting?",
      "What would happen if you simply allowed {term} to be present without judgment?",
      "What does {term} want that your repeated rejection keeps preventing?"
    ],
    "wittgenstein": [
      "What are you using the word {term} to mean that makes it rejectable?",
      "Where does your refusal of {term} come from the word rather than the thing?",
      "What would {term} look like described in completely different language?",
      "Is your rejection of {term} a logical position or a linguistic habit?",
      "What cannot be said about {term} that your repeated rejection is circling?"
    ]
  },
  "absence": {
    "rilke": [
      "What is {term} not yet ready to be — in you?",
      "What would {term} require you to have lived before it could appear here?",
      "Is {term} absent because it has not arrived yet or because you are not yet the person it arrives to?",
      "What is {term} becoming in the silence before you can write it?",
      "What would it mean to trust that {term} is present even in its absence?",
      "What is {term} waiting for before it enters the room?"
    ],
    "rovelli": [
      "What is the shape of the space {term} would occupy if it were here?",
      "What does the absence of {term} allow to exist that its presence would displace?",
      "Is {term} absent or is it present in a form you do not yet have instruments to measure?",
      "What would {term} look like if absence and presence were not opposites but states of the same thing?",
      "What is {term} doing in the places in your map that you cannot see?",
      "What would change in the whole system if {term} entered it?"
    ],
    "weil": [
      "What would full attention to {term} require you to feel that you are currently not feeling?",
      "What is the cost of {term}'s absence that you have arranged not to notice?",
      "What in {term} are you refusing to look at by refusing to write about it?",
      "What would it mean to give {term} your attention even before you have the words for it?",
      "Where does the absence of {term} come from genuine limits and where from careful avoidance?",
      "What would {term} look like if you looked at it the way you look at something you are not afraid of?"
    ],
    "socrates": [
      "What assumption about yourself makes the absence of {term} feel natural?",
      "What question about {term} have you never allowed yourself to ask?",
      "What would examining {term} reveal that you have arranged not to examine?",
      "What belief depends on {term} remaining unwritten?",
      "What does the absence of {term} in your writing protect you from knowing?"
    ],
    "descartes": [
      "What would remain of your map if {term} were present in it?",
      "What are you certain of that requires {term} to stay absent?",
      "If you doubted the reasons {term} is not here — what would you find?",
      "What foundation of your thinking depends on not writing about {term}?",
      "What could not be doubted about {term} if you allowed yourself to think it?"
    ],
    "camus": [
      "What absurdity does the absence of {term} allow you to keep at a distance?",
      "If {term} has no comfortable place in your map — what would it mean to include it anyway?",
      "What would revolt against {term}'s absence look like?",
      "Is the absence of {term} a form of honesty or a form of managed blindness?",
      "What if including {term} is not about resolution but about refusing to look away?"
    ],
    "einstein": [
      "What does your map look like from the position that {term} would occupy?",
      "What frame of reference makes {term} invisible — and who holds that frame?",
      "What changes about the whole map if {term} enters it?",
      "What is the coordinate system that excludes {term} — and did you choose it?",
      "What would {term} make measurable that is currently unmeasurable in your writing?"
    ],
    "spinoza": [
      "What necessity does the absence of {term} serve in the larger pattern of your map?",
      "What would it mean if {term}'s absence could not have been otherwise at this point in your writing?",
      "What deeper order is {term}'s absence part of?",
      "What is {term} doing by being absent that it could not do by being present?",
      "What would the complete version of your map necessarily include — and what does that tell you?"
    ],
    "laotzu": [
      "What would {term} do in your map if you stopped keeping it out?",
      "Where does the effort of not writing about {term} cost more than writing about it would?",
      "What is the natural presence of {term} that your writing keeps interrupting?",
      "What would happen to your map if {term} were simply allowed to enter?",
      "What does {term} want to say that you have not yet allowed?"
    ],
    "wittgenstein": [
      "What can you not say because you have no language for {term} yet?",
      "Where does the absence of {term} come from the limits of your language rather than the limits of your experience?",
      "What word would you need to write about {term} that you do not yet have?",
      "Is {term} absent because it is unspeakable or because you have decided not to speak it?",
      "What would {term} sound like in your own voice — even approximately?"
    ]
  }
};

  function cueRetireKey(type, term) {
    return String(type) + '|' + String(term);
  }

  function clamp01(n) {
    if (n == null || isNaN(n)) return 0;
    return Math.max(0, Math.min(1, n));
  }

  function computeWeatherState(snap, ctx) {
    ctx = ctx || {};
    if (!snap) return { state: 'calm', label: null, intensity: 0 };
    if (ctx.post_craft) return { state: 'calm', label: null, intensity: 0 };

    var pv = snap.posture_vector || {};
    var coherence = pv.coherence != null ? pv.coherence : 0;
    var resistance = pv.resistance != null ? pv.resistance : 0;
    var openN = snap.open_bridges_count != null
      ? snap.open_bridges_count
      : (snap.open_bridges ? snap.open_bridges.length : 0);
    var orbitN = (snap.perpetual_orbit_terms && snap.perpetual_orbit_terms.length) || 0;
    var resurgent = (snap.half_life && snap.half_life.resurgent) || [];
    var resistanceDelta = ctx.resistance_delta != null ? ctx.resistance_delta : 0;
    var daysSinceWrite = ctx.days_since_write != null ? ctx.days_since_write : null;
    var prevTurbulent = ctx.previous_weather_turbulent === true;

    var candidates = [];

    if (resurgent.length) {
      candidates.push({
        state: 'electrical',
        intensity: clamp01(0.5 + resurgent.length * 0.15)
      });
    }
    if (openN >= 2 || orbitN >= 3) {
      candidates.push({
        state: 'pressure',
        intensity: clamp01(Math.max(openN / 4, orbitN / 5))
      });
    }
    if (resistanceDelta >= 0.3) {
      candidates.push({
        state: 'front',
        intensity: clamp01(resistanceDelta)
      });
    }
    if (prevTurbulent && resistanceDelta <= -0.15 && coherence >= 0.5) {
      candidates.push({
        state: 'after_storm',
        intensity: clamp01(0.4 + Math.abs(resistanceDelta))
      });
    }
    if (daysSinceWrite != null && daysSinceWrite >= 14) {
      candidates.push({
        state: 'drought',
        intensity: clamp01(Math.min(1, daysSinceWrite / 30))
      });
    }

    if (coherence >= 0.85 && resistance < 0.3 && openN === 0 && !resurgent.length) {
      return { state: 'calm', label: null, intensity: 0 };
    }

    if (!candidates.length) {
      return { state: 'calm', label: null, intensity: 0 };
    }

    candidates.sort(function (a, b) {
      return WEATHER_PRIORITY.indexOf(a.state) - WEATHER_PRIORITY.indexOf(b.state);
    });
    var pick = candidates[0];
    return {
      state: pick.state,
      label: WEATHER_LABELS[pick.state] || pick.state,
      intensity: pick.intensity
    };
  }

  function selectVoice(intensity, opts) {
    opts = opts || {};
    var bucket;
    if (intensity > 0.66) bucket = VOICE_BUCKETS.high;
    else if (intensity >= 0.33) bucket = VOICE_BUCKETS.mid;
    else bucket = VOICE_BUCKETS.low;

    if (opts.first_cue_on_term && !opts.term_engaged_before) {
      bucket = VOICE_BUCKETS.mid.concat(VOICE_BUCKETS.low);
    }

    return bucket[Math.floor(Math.random() * bucket.length)];
  }

  function parseDenialTerms(snap) {
    var out = [];
    (snap.anomalies || []).forEach(function (a) {
      if (typeof a === 'string' && a.indexOf('denial_sediment:') === 0) {
        out.push(a.slice('denial_sediment:'.length));
      }
    });
    return out;
  }

  function firstOpenBridgeTerm(snap) {
    var obs = snap.open_bridges || [];
    for (var i = 0; i < obs.length; i++) {
      var terms = obs[i].terms;
      if (terms && terms.length) return terms[0];
    }
    return null;
  }

  function buildCandidates(snap) {
    var list = [];
    if (!snap) return list;

    if (snap.perpetual_orbit_terms && snap.perpetual_orbit_terms.length) {
      list.push({ type: 'orbit', term: snap.perpetual_orbit_terms[0] });
    }
    var bridgeTerm = firstOpenBridgeTerm(snap);
    if (bridgeTerm) list.push({ type: 'bridge', term: bridgeTerm });

    var resurgent = (snap.half_life && snap.half_life.resurgent) || [];
    if (resurgent.length) list.push({ type: 'resurgence', term: resurgent[0] });

    var denial = snap.denial_sediment_terms || parseDenialTerms(snap);
    if (denial.length) list.push({ type: 'denial', term: denial[0] });

    if (ENABLE_ABSENCE_CUES && snap.void_hints && snap.void_hints.length) {
      list.push({ type: 'absence', term: snap.void_hints[0] });
    }

    return list;
  }

  function cuesAllowedForWeather(weather) {
    if (!weather) return false;
    if (weather.state === 'calm' || weather.state === 'drought') return false;
    return true;
  }

  function generateWitnessCues(snap, opts) {
    opts = opts || {};
    var weather = computeWeatherState(snap, opts.context);
    if (!cuesAllowedForWeather(weather)) return [];

    var retired = opts.retiredKeys || {};
    var cues = [];
    var usedSignals = new Set();
    var candidates = buildCandidates(snap);

    for (var i = 0; i < candidates.length; i++) {
      if (cues.length >= 3) break;
      var candidate = candidates[i];
      if (usedSignals.has(candidate.type)) continue;

      var key = cueRetireKey(candidate.type, candidate.term);
      if (retired[key]) continue;

      var voice = selectVoice(weather.intensity, {
        first_cue_on_term: opts.first_cue_on_term,
        term_engaged_before: opts.engagedTerms && opts.engagedTerms[candidate.term]
      });
      var pool = CUES_MATRIX[candidate.type] && CUES_MATRIX[candidate.type][voice];
      if (!pool || !pool.length) continue;

      var question = pool[Math.floor(Math.random() * pool.length)]
        .replace(/\{term\}/g, candidate.term);

      cues.push({
        source_type: candidate.type,
        source_term: candidate.term,
        question_text: question
      });
      usedSignals.add(candidate.type);
    }

    return cues;
  }

  var api = {
    VOICE_BUCKETS: VOICE_BUCKETS,
    CUES_MATRIX: CUES_MATRIX,
    ENABLE_ABSENCE_CUES: ENABLE_ABSENCE_CUES,
    cueRetireKey: cueRetireKey,
    computeWeatherState: computeWeatherState,
    generateWitnessCues: generateWitnessCues,
    buildCandidates: buildCandidates
  };

  if (typeof module !== 'undefined' && module.exports) {
    module.exports = api;
  }
  global.WitnessWeather = api;
})(typeof window !== 'undefined' ? window : globalThis);
